VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "vagrant.example.com"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/playbook.yml"
    end

  


end
